baseURL = "https://yitaohe.com/"
languageCode = "zh-cn"
title = "yitaohe.com"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  overview = "/overview/"
  blogs = "/blogs/:primary_category/:slug/"
  comments = "/comments/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5

