baseURL = "https://yitaohe.com/"
languageCode = "zh-cn"
title = "yitaohe.com"
defaultContentLanguage = "en"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  overview = "/overview/"
  blogs = "/blogs/:sections[1]/:slug/"
  comments = "/comments/"

[outputs]
  home = ["HTML", "RSS"]

[markup.goldmark.renderer]
  unsafe = true

[languages.zh]
  contentDir = "content/zh"
  languageCode = "zh-cn"
  weight = 1
  languageName = "中文"
  title = "yitaohe.com"

[languages.en]
  contentDir = "content/en"
  languageCode = "en"
  weight = 2
  languageName = "English"
  title = "yitaohe.com"

[sitemap]
  changefreq = "weekly"
  priority = 0.5

