baseURL = "https://yitaohe.com/"
languageCode = "zh-cn"
title = "yitaohe.com"

[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  overview = "/overview/"
  # content/blogs/system-design/post/ -> /blogs/system-design/post/
  blogs = "/blogs/:sections[1]/:slug/"
  comments = "/comments/"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "weekly"
  priority = 0.5

